### ISSUE TITLE
A problem about the kl loss

### ISSUE THREAD

**Issue by scutcsq** [hcy71o/SC-CNN#4]
Hi, I tried to run the code, but the kl_loss is always infinity.

**Comment by hcy71o** [comment]
did you use the custom dataset?

**Comment by scutcsq** [comment]
I used the VCTK corpus and followed the setting.

**Comment by hcy71o** [comment]
That's weird I'll check it.. I guess it might be due to the recent commit adding einsum

**Comment by hcy71o** [comment]
Plz try to disable the fp16 trianing option, I found the same problem when training other flow-based models.
