### ISSUE TITLE
How much did you train with VCTK Dataset?

### ISSUE THREAD

**Issue by kdrkdrkdr** [hcy71o/SC-CNN#7]
Thank you for your hard work!
No other than that, I currently set the batch size value to 32 with one RTX 4090 and conducted about 800K of learning. But it doesn't produce a proper voice. Can you tell me what the problem is?
For your information, I used SC-Transfer.

**Comment by hcy71o** [comment]
I trained 800k steps (with single GPU) with batch size 64. 
I recommend to utilize LibriTTS-R (or other additional dataset) for larger context coverage, 
If loss values diverge, you can turn off the fp16 training option.
